#!/usr/bin/env sh

# Argument check
if [ $# -lt 1 ]; then
  echo "This script requires at least 1 argument.

Usage: ./new.sh title-string"
  exit 1
fi

# Check if directory doesn't exists.
DIRECTORY="_posts"
if [ ! -d ${DIRECTORY} ]; then
  echo "${DIRECTORY} directory doesn't exist."
  exit 1
fi

# Generate file name and create markdown file.
NAME=$1
DATE=`date "+%Y-%m-%d"`
FILE=${DATE}-${NAME}.markdown
if [ -f ${DIRECTORY}/${FILE} ]; then
  echo "The file '${DIRECTORY}/${FILE}' already exist."
else
  cat << EOT >> ${DIRECTORY}/${FILE}
---
layout: post
title: "$NAME"
date: `date "+%Y-%m-%d %H:%M:%S %z"`
categories: 
---
EOT
  echo "The file '${DIRECTORY}/${FILE}' can be created"
fi
